apiVersion: apps/v1
kind: Deployment
metadata:
  name: iissample
  labels:
    app: iissample
spec:
  replicas: 1
  template:
    metadata:
      name: iissample
      labels:
        app: iissample
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: iissample
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .5
            memory: 400M
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: regcred
  selector:
    matchLabels:
      app: iissample
---
apiVersion: v1
kind: Service
metadata:
  name: iissample
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: iissample
